cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'git'
brew 'git-flow-avh'
brew 'node'
brew 'npm'
# brew 'nvm'
brew 'zsh'
brew 'wget'

cask 'visual-studio-code'
cask 'selfcontrol'
cask 'slack'
cask 'spotify'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'iterm2'
# cask '1password'
cask 'dropbox'